### ISSUE TITLE
Header responsive issues

### ISSUE THREAD

**Issue by martoio** [MymboYumbo/assignment_04#1]
The best way to handle the responsive issues on your header is to just make sure you set a specific height on the header at each breakpoint.

For example:
```css
@media only screen and (max-width: 480px){
    header {
        height: 200px;
    }    
}
```
And then for `the_rest`, you would apply a top of `200px`. It's not the best design, but that way you can make sure your header doesn't cut off.
